abstract: A Common Gateway Interface (CGI) Class
author: Mark Lawrence <nomad@null.net>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: GPL
name: NCGI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Encode: 0
  Time::HiRes: 0
  XML::API: 0.19
  perl: 5.6.0
version: 0.08
