name: NCGI
module_name: NCGI
version: 0.04
abstract: A New CGI Module
author: Mark Lawrence <nomad@null.net>
license: unknown
distribution_type: module
requires:
  debug: 0
  XML::API: 0.05
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
