name: NCGI
module_name: NCGI
version: 0.05
abstract: A New CGI Module
author: Mark Lawrence <nomad@null.net>
license: unknown
distribution_type: module
requires:
  Log::Delta: 0.02
  XML::API: 0.07
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.34
